site_name: ClipSlide
docs_dir: docs

nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide:
      - Basic Usage: user-guide/basic-usage.md
      - Search: user-guide/search.md
      - Albums: user-guide/albums.md
      - Controls: user-guide/controls.md
  - Configuration: configuration.md
  - Developer Guide:
      - Architecture: developer/architecture.md
      - API: developer/api.md
      - Frontend: developer/frontend.md
  - Troubleshooting: troubleshooting.md

theme:
  name: material

