[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "clipshow"
version = "0.2.0"
description = "Image indexing and retrieval using CLIP"
authors = [
    { name = "Lincoln Stein", email = "lincoln.stein@gmail.com" }
]
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "torch",
    "Pillow",
    "clip-anytorch",
    "fastapi",
    "uvicorn",
    "python-multipart",
    "jinja2",
    "pydantic",
    "scikit-learn",
    "networkx",
    "tqdm",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
index_images = "backend.imagetool:main"
update_images = "backend.imagetool:main"
search_images = "backend.imagetool:main"
search_text = "backend.imagetool:main"
find_duplicate_images = "backend.imagetool:main"
