[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "clipslide"
version = "0.3.0"
description = "Image indexing and retrieval using CLIP"
authors = [
    { name = "Lincoln Stein", email = "lincoln.stein@gmail.com" }
]
requires-python = ">=3.8"
dependencies = [
    "Pillow",
    "clip-anytorch",
    "dash",
    "fastapi",
    "jinja2",
    "networkx",
    "numpy",
    "pandas",
    "platformdirs",
    "pydantic",
    "python-multipart",
    "PyYAML",
    "requests",
    "scikit-learn",
    "torch",
    "tqdm",
    "umap",
    "uvicorn",
]

[project.optional-dependencies]
testing = [
    "pytest",
    "pytest-cov",
    "httpx",
    "asynctest",
    "pytest-asyncio",
]

[tool.setuptools.packages.find]
where = ["."]  # Look in the current directory (repo root)
include = ["clipslide*"]  # Include clipslide package and subpackages

# Include package data files
[tool.setuptools.package-data]
"clipslide.frontend" = ["static/*", "templates/*"]

[project.scripts]
index_images = "clipslide.backend.imagetool:main"
update_images = "clipslide.backend.imagetool:main"
search_images = "clipslide.backend.imagetool:main"
search_text = "clipslide.backend.imagetool:main"
find_duplicate_images = "clipslide.backend.imagetool:main"
start_slideshow = "clipslide.backend.clipslide_server:main"
